### ISSUE TITLE
TODO: Duplicate removal using UMIs

### ISSUE THREAD

**Issue by DeplanckeLab** [DeplanckeLab/BRB-seqTools#1]

**Comment by DeplanckeLab** [comment]
This was "kinda" implemented along with the AnnotateBAM feature.
After annotated, one can use Picard MarkDuplicates with the following options
   BARCODE_TAG=BC
   READ_ONE_BARCODE_TAG=BX

**Comment by orionzhou** [comment]
Hi, after successfully running AnnotateBAM, I got:

> Created 345 temporary BAM files
> 23796 Unique genes were detected (at least one read).
> 287636366 'Mapped' reads (83.52%)
> 2529909 'Ambiguous' reads (0.73%)
> 54237296 'No Features' reads (15.75%)
> 0 'Not Unique' reads (0%)
> 0 'Not Aligned' reads (0%)
> 0 'Too Low aQual' reads (0%)

I then ran Picard Markduplicates:

> picard MarkDuplicates \
>   BARCODE_TAG=BC READ_ONE_BARCODE_TAG=BX \
>   I=hisat2.sorted.bam.annotated.bam O=hisat2.sorted.md.bam \
>   M=hisat2.sorted.md.txt

which throws this error:

> Exception in thread "main" picard.PicardException: UMI found with illegal characters.  UMIs must match the regular expression ^[ATCGNatcgn-]*$.

Upon checking the annotated BAM I found some reads with BC tag "Unknown", could that be the cause?

> A00223:219:HCTCKDRXX:1:2101:10013:28072 16      B01     197046487       60      92M     *       0       0       TGTCACAAGTCACCATGAAACACGGTACAGGGAAGGAGGCAGGGAACAACGTCTCAGCTGGATCTATTTTTTTTTATGAGATAGTACAGAGT    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,F,,,FFFFFFFFFFFFFFF:FFFFFFFFF:FFFFFFFFFFFFFFFFFFFFFF    BC:Z:Unknown    MD:Z:34A4G52    XG:i:0  NH:i:1  NM:i:2  XM:i:2  XN:i:0  CO:Z:Zm00001d031636     XO:i:0  AS:i:-8 QT:Z:FFFFFF     YT:Z:UU BX:Z:CAAAAGCGCGCGGAC    QX:Z:FFF:FFFFFFFFFFF
> A00223:219:HCTCKDRXX:1:2101:10013:28166 0       B08     30574921        60      92M     *       0       0       TAATGTGGCTGAGTAACTGTCCAATCCAAGCGTTTCTGCCCCCTTTATTTCGTGCCATAAGAAGGAAGTACCATGAATGAACATTATAAAGC    FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:F    BC:Z:GCGTGG     MD:Z:92 XG:i:0  NH:i:1  NM:i:0  XM:i:0  XN:i:0  CO:Z:Zm00001d009023     XO:i:0  AS:i:0  QT:Z:FFFFFF     YT:Z:UU BX:Z:TCTACGTCTGGGGAG    QX:Z:FFFFFFFFFFFFFFF
