### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by tomkinsc** [DeplanckeLab/BRB-seqTools#2]
Hello, 
What license is BRB-seqTools distributed under (MIT, GPL, something else.)? I'd like to add a package for `BRB-seqTools` to [bioconda](https://bioconda.github.io/), but in order to do so it would be helpful to know which license to list and that the software can indeed be (re)distributed.

Thank you!

**Comment by DeplanckeLab** [comment]
Hey. Sorry for the late Easter reply.
I've added a LICENSE file.

**Comment by tomkinsc** [comment]
Thanks for adding a license. One question since most of the other bioconda software is GPL/MIT/BSD-licensed: Would you consider distribution via Bioconda to be in violation of the non-commercial constraint of the specified Creative Commons BY-NC-SA license? Creative Commons provides [this guidance](https://wiki.creativecommons.org/wiki/NonCommercial_interpretation) on the NonCommercial element.  

Bioconda includes [~4000](https://bioconda.github.io/recipes.html) open source free software tools that are heavily used by those in the academe and at non-profits, but we do not disallow use by those in corporations. The goal is to make bioinformatics software easily available to everyone, free of charge, but the tools need to allow for distribution regardless of intended usage (since we cannot control who installs packages from bioconda). 

If you support distribution of BRB-seqTools via bioconda and the [Anaconda Cloud](https://anaconda.org/bioconda), perhaps the license could be amended to include explicit permission for bioconda to redistribute it?

Thanks,
Chris

**Comment by lecorguille** [comment]
Hi here,
I'm interesting in providing this tool via a Conda package to our users

Any news @VincentGardeux ?

**Comment by VincentGardeux** [comment]
Hi,

We did not plan to change the license of this repo.

I can redirect you to a more recent tool that we develop and performs similar tasks (except the demultiplexing task) and is undergoing development with a GPL license here: [FastReadCounter](https://github.com/DeplanckeLab/FastReadCounter)

Cheers
