### ISSUE TITLE
Issure with barcode file when running CreateDGEMatrix

### ISSUE THREAD

**Issue by avitalsteiman** [DeplanckeLab/BRB-seqTools#4]
I ran:
```
$ java -jar BRBseqTools.1.3.jar CreateDGEMatrix -f
 ../Library1_R1_001.fastq.gz -b
 Library1_R2_001.trimmed_Aligned.out.bam -c ../lib_example_barcodes.txt
-gtf  ~/bioninformatics/genomes/hg38/Homo_sapiens.GRCh38.98.chr.gtf  -p BU
-UMI 10
```

And received the following output:

> BRBSeqTools 1.3 [CreateDGEMatrix]
> 
> Barcode Pattern = BU
> Maximum allowed Hamming distance for sequencing error correction [Barcode]= 1
> Maximum allowed Hamming distance for sequencing error correction [UMI] = 0
> ChunkSize = 1000000 i.e. no more than 1000000 reads will be stored in RAM.
> Stranded = YES
> No output Folder is specified, using default one:"/home/star_bam/..".
> You can specify an output path by using the '-o' option.
> No folder for temporary generated files is specified, using output folder
> as default:"/home/star_bam/..".
> You can specify a temporary folder by using the '-t' option.
> Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
>        at tools.Utils.readConfig(Utils.java:333)
>       at BRBseqTools.main(BRBseqTools.java:34)

I'm attaching my barcode file, since the problem appears to be related.
[lib_example_barcodes.txt](https://github.com/DeplanckeLab/BRB-seqTools/files/3766154/lib_example_barcodes.txt)

Thanks,
Avital

**Comment by VincentGardeux** [comment]
Hello @avitalsteiman,

There was an issue handling empty lines in the barcode file.
I solved it.

Can you try again with the novel .jar file?

Cheers

**Comment by avitalsteiman** [comment]
Hi,
Thank you for your answer.
Yes it works now.
BTW, I'm not sure if this is a problem on your end or mine, but when trying to download the new jar file I got this error:

> ERROR: cannot verify raw.githubusercontent.com's certificate, issued by ‘CN=Cisco Umbrella Secondary SubCA fra-SG,O=Cisco’:
>   Unable to locally verify the issuer's authority.
> To connect to raw.githubusercontent.com insecurely, use `--no-check-certificate'.

Appreciate the help,
Avital
