### ISSUE TITLE
one issue in CreateDGEMatrix

### ISSUE THREAD

**Issue by Rhine86** [DeplanckeLab/BRB-seqTools#6]
Hi, 
 I ran 'java -jar BRBseqTools-1.6.jar CreateDGEMatrix -f BRBeq_raw_1.fq.gz -b BAM/Aligned.out.bam -c lib_barcodes.txt -gtf Mus_musculus.GRCm38.102.gtf -p BU -I 10' and got the following error
 'BRBSeqTools 1.6 [CreateDGEMatrix]

Barcode Pattern = BU
Maximum allowed Hamming distance for sequencing error correction [Barcode] = 1
Maximum allowed Hamming distance for sequencing error correction [UMI] = 0
ChunkSize = 1000000 i.e. no more than 1000000 reads will be stored in RAM.
Stranded = YES
Multiple mapped reads will be DISCARDED
No output Folder is specified, using default one: "211223_BRB_test". You can specify an output path by using the '-o' option.
No folder for temporary generated files is specified, using output folder as default: "211223_BRB_test". You can specify a temporary folder by using the '-t' option.
Config: B1 contains 6 barcodes: [ TTAACT TAAAAC CCCCAC AAACAT ATATGA GGACAT ]
Config: B1 length [#nucleotides] = 6

Analyzing barcode Pattern...
According to barcode pattern, reads of R1 FastQ file should contain 16 characters.

Reading GTF file provided: Mus_musculus.GRCm38.102.gtf
843712 'exons' are annotating 55487 unique gene_ids in the provided GTF file.

Reading reads barcodes/UMI from the R1 fastq file...
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -2
        at java.lang.String.substring(String.java:1967)
        at tools.Utils.nextRead(Utils.java:96)
        at tools.Utils.readR1Fastq(Utils.java:273)
        at BRBseqTools.main(BRBseqTools.java:42)'

My barcode file is
[lib_barcodes.txt](https://github.com/DeplanckeLab/BRB-seqTools/files/7778959/lib_barcodes.txt)
and my R1 file looks like this 
![image](https://user-images.githubusercontent.com/3023363/147521762-7082385b-82f5-4e6d-9035-0eb71ea14767.png)

Can you help me? Thank you!
Yan

**Comment by VincentGardeux** [comment]
Sorry did not see your issue before.
You probably solved this already?

In your command-line it should be:
-UMI 10 and not -I 10

**Comment by VincentGardeux** [comment]
Actually, this was not the error.
[Raised by another user](https://github.com/DeplanckeLab/BRB-seqTools/issues/9), it was coming from the read name format that was not yet handled.
It is fixed now in v1.6.1

**Comment by VincentGardeux** [comment]
Actually, this was not the error.
[Raised by another user](https://github.com/DeplanckeLab/BRB-seqTools/issues/9), it was coming from the read name format that was not yet handled.
It is fixed now in v1.6.1
