### ISSUE TITLE
BRBseqTools.jar 1.6 CreateDGEMatrix generation issue

### ISSUE THREAD

**Issue by refinedfan** [DeplanckeLab/BRB-seqTools#9]
Hi~
I have been trying to fix the issue for several days. When I come to the last step of CreateDGEMatrix, I alwasy get an error info.
The command I used was: “java -jar BRBseqTools-1.6.jar CreateDGEMatrix -f subsample_V350083497_L01_read_1.fq.gz -b BAM/subsample_V350083497_L01_read_2.bam -c PPI_sample_to_barcode.txt -gtf Mus_musculus.GRCm38.99.gtf -p BU -UMI 14”

The error information was:

“BRBSeqTools 1.6 [CreateDGEMatrix]

Barcode Pattern = BU
Maximum allowed Hamming distance for sequencing error correction [Barcode] = 1
Maximum allowed Hamming distance for sequencing error correction [UMI] = 0
ChunkSize = 1000000 i.e. no more than 1000000 reads will be stored in RAM.
Stranded = YES
Multiple mapped reads will be DISCARDED
Config: B1 contains 48 barcodes: [ CACGTAGCTAGACG CAGCAGCGCTGACA TATGTACGTAGAGA CAGATCGCTCTGCG AACATGGCACGGAA ATGCTATCTAGACA TAACCTAACTTCAC ACCAATCCGTATAA CTCGTGCCTCAGGA CTCCTAACACAGCC ATGCAATTACACCG ATACCGTTGGAGGA ACCAACTTAGACAA TCAGCGTGTCGTCA ATTCCGCTCTGAGG ACCGATGTGCCGGA CTAAGGAAGGACCG TTCTGAGGCGATGG ACGAGCAGATGCAG ATCCTAAGTGGAGG TTCAATCTCCTTAG CTCGGTTCGAATGC ATACGATGCTGCGC TACACTATAGCTAG CAAGTATAAGGAAC AAGCCTTAGGCCGC CTGATATGCAGCGA AATGTGTGGATACC ATGCTGCAACGGCA CCATATTGAAGCAC TCGATTGGTAATGG CTTGATAAGCCAGG TTCATGGTAGAGAG ACGCTCCTAACGGC CTCAATTAGAGACC TCGATCTTCGGCAG AACAACCGAAGTAA AACTAGTATCCGGA ACGCAGCGAGCAGA TCCAAGGCATTAAG TCGATGCTATATGA TATGACTGCATGCG ACAAGGTTCCGCCG ACCGGATAACGGAA CCACGTTCCGGTAG ACTTAAGGTCCAAC TCCAGAAGGCAACA CTGCTCATGAGAGA ]
Config: B1 length [#nucleotides] = 14

Analyzing barcode Pattern...
According to barcode pattern, reads of R1 FastQ file should contain 28 characters.

Reading GTF file provided: /home/projects/ku_00009/people/fanzha/PPI/RNAseq/L01/Mus_musculus.GRCm38.99.gtf
843183 'exons' are annotating 55471 unique gene_ids in the provided GTF file.

**Reading reads barcodes/UMI from the R1 fastq file...
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -2
        at java.lang.String.substring(String.java:1967)
        at tools.Utils.nextRead(Utils.java:96)
        at tools.Utils.readR1Fastq(Utils.java:273)
        at BRBseqTools.main(BRBseqTools.java:42)”**

I have a read1 with 28bp, 14bp barcode and followed by UMI.

My Read1 file looks like this:
![image](https://github.com/DeplanckeLab/BRB-seqTools/assets/48325953/92bb2bb6-a42e-4281-9c4b-73262a0af579)

The barcode file looks like this:
![image](https://github.com/DeplanckeLab/BRB-seqTools/assets/48325953/3f3d29e5-63ef-4ee5-9b44-ecaf3c1bd19f)

How should I fix the issue? Thank you very much.

**Comment by VincentGardeux** [comment]
Hi Fan,

Thanks for raising this issue.
It comes from the specific read-names format that was not handled.

I fixed it in v.1.6.1

Cheers
